# build environment
FROM node:13.12.0-alpine as build
WORKDIR /trena_dashboard
ENV PATH /trena_dashboard/node_modules/.bin:$PATH
COPY package.json ./
RUN npm install
COPY . ./
RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /trena_dashboard/build /usr/share/nginx/html/dashboard
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]